export { default as Home } from './Home.jsx'
export { default as DailyHoroscope } from './DailyHoroscope.jsx'
export { default as LoveCompatibility } from './LoveCompatibility.jsx'
export { default as PremiumFeatures } from './PremiumFeatures.jsx'
export { default as Profile } from './Profile.jsx'
export { default as NotFound } from './NotFound.jsx'
